'use strict';
const $=s=>document.querySelector(s), audio=$('#audio');
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem('grove:'+k))??f}catch{return f}};
const save=(k,v)=>{try{localStorage.setItem('grove:'+k,JSON.stringify(v))}catch{notice('Browser storage is full or unavailable. Changes may not be saved.')}};
const state={songs:[],view:'all',favorites:read('favorites',[]),history:read('history',[]),playlists:read('playlists',[]),queue:[],current:null,shuffle:false,repeat:0,cast:null,remote:null,host:null,last:0};
let noticeTimer,castPlayer,castController,loading=false,polling=false,installPrompt=null,pendingPlaylistSong=null,renameId=null;
function notice(t){$('#notice').textContent=t;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').textContent='',6500)}
function el(tag,props={},children=[]){const n=document.createElement(tag);for(const [k,v] of Object.entries(props)){if(k==='text')n.textContent=v;else if(k==='class')n.className=v;else if(k.startsWith('on'))n.addEventListener(k.slice(2),v);else n.setAttribute(k,v)}for(const c of children)n.append(c);return n}
const button=(text,label,fn)=>el('button',{text,class:'icon','aria-label':label,onclick:fn});
const getSong=id=>state.songs.find(s=>s.id===id);
const clock=v=>Number.isFinite(v)?`${Math.floor(v/60)}:${String(Math.floor(v%60)).padStart(2,'0')}`:'0:00';
function validUrl(u){try{const x=new URL(u);return x.protocol==='https:'&&x.hostname==='audio.soundbreak.ai'&&!x.username&&!x.password&&/^\/[a-zA-Z0-9/_-]+\.mp3$/.test(x.pathname)&&!x.port&&!x.search&&!x.hash}catch{return false}}
function visible(){let a=state.songs;if(state.view==='favorites')a=a.filter(s=>state.favorites.includes(s.id));else if(state.view==='history')a=state.history.map(getSong).filter(Boolean);else if(state.view==='queue')a=state.queue.map(getSong).filter(Boolean);else if(state.view.startsWith('p:'))a=(state.playlists.find(p=>'p:'+p.id===state.view)?.songs||[]).map(getSong).filter(Boolean);const q=$('#search').value.toLowerCase();return a.filter(s=>(s.title+' '+s.genre+' '+s.version).toLowerCase().includes(q))}
function render(){const list=visible(),p=state.playlists.find(p=>'p:'+p.id===state.view);$('#viewTitle').textContent=p?.name||({all:'All songs',favorites:'Favorites',history:'Recently played',queue:'Play queue'}[state.view]||'All songs');$('#songCount').textContent=`${list.length} song${list.length===1?'':'s'}`;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));$('#playlists').replaceChildren(...state.playlists.map(p=>el('button',{text:'♫  '+p.name,class:state.view==='p:'+p.id?'active':'',onclick:()=>{state.view='p:'+p.id;render()}})));$('#playlistActions').replaceChildren();if(p){$('#playlistActions').append(el('button',{text:'Rename',onclick:()=>{renameId=p.id;$('#playlistHeading').textContent='Rename playlist';$('#playlistForm').elements.name.value=p.name;$('#playlistDialog').showModal()}}),el('button',{text:'Delete playlist',onclick:()=>{state.playlists=state.playlists.filter(x=>x.id!==p.id);save('playlists',state.playlists);state.view='all';render()}}))}if(state.view==='queue')$('#playlistActions').append(el('button',{text:'Clear queue',onclick:()=>{if(state.remote)return command('clearQueue');state.queue=[];render()}}));$('#songs').replaceChildren(...list.map((s,i)=>{const n=el('div',{class:'song'});n.append(el('span',{class:'number',text:String(i+1)}),el('button',{class:'song-play'+(state.current?.id===s.id?' current':''),onclick:()=>choose(s,list,i),'aria-label':'Play '+s.title+' '+s.genre+' '+s.version},[el('img',{src:s.art||'art-0.svg',alt:'',loading:'lazy'}),el('span',{},[el('strong',{text:s.title}),el('small',{text:s.genre+' · '+s.version})])]),el('span',{class:'genre',text:s.genre}),button(state.favorites.includes(s.id)?'♥':'♡','Favorite '+s.title,()=>favorite(s.id)),button('＋','Add '+s.title+' to queue',()=>{if(state.remote)command('enqueue',{song:s});else{state.queue.push(s.id);render();notice('Added to queue')}}),button('⋯','Add '+s.title+' to playlist',()=>choosePlaylist(s.id)));if(p)n.append(button('−','Remove from playlist',()=>{p.songs=p.songs.filter(id=>id!==s.id);save('playlists',state.playlists);render()}));if(state.view==='queue')n.append(button('×','Remove queued song',()=>{const index=state.queue.indexOf(s.id);if(state.remote)command('removeQueue',{index});else{state.queue.splice(index,1);render()}}));return n}));if(!list.length)$('#songs').append(el('p',{class:'empty',text:state.view==='queue'?'Your queue is empty. Use + beside a song to add it.':'No songs here yet. Try another search or add songs from your library.'}));$('#nowFavorite').textContent=state.current&&state.favorites.includes(state.current.id)?'♥':'♡'}
function favorite(id){if(!id)return;state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save('favorites',state.favorites);render()}
function choosePlaylist(id){pendingPlaylistSong=id;if(!state.playlists.length){newPlaylist();return}$('#playlistChoices').replaceChildren(...state.playlists.map(p=>el('button',{text:p.name,type:'button',onclick:()=>{if(!p.songs.includes(id))p.songs.push(id);save('playlists',state.playlists);$('#choosePlaylist').close();render();notice('Added to '+p.name)}})));$('#choosePlaylist').showModal()}
function newPlaylist(){renameId=null;$('#playlistHeading').textContent='Create playlist';$('#playlistForm').reset();$('#playlistDialog').showModal()}
async function choose(s,list,i){if(!s)return notice('Choose a collection with songs first.');if(state.remote)return command('play',{song:s,queue:list.slice(i+1).map(x=>x.id)});state.queue=list.slice(i+1).map(x=>x.id);await play(s)}
async function play(s){if(loading)return;if(!s||!validUrl(s.url))return;loading=true;state.current=s;$('#nowTitle').textContent=s.title;$('#nowGenre').textContent=s.genre+' · '+s.version;$('#nowArt').src=s.art||'art-0.svg';try{if(state.cast){const m=new chrome.cast.media.MediaInfo(s.url,'audio/mpeg');m.metadata=new chrome.cast.media.MusicTrackMediaMetadata();m.metadata.title=s.title;m.metadata.artist='SoundBreak · '+s.genre;m.metadata.images=[new chrome.cast.Image(new URL(s.art||'art-0.svg',location.href).href)];await state.cast.loadMedia(new chrome.cast.media.LoadRequest(m));audio.pause()}else{audio.src=s.url;await audio.play()}state.history=[s.id,...state.history.filter(id=>id!==s.id)].slice(0,100);save('history',state.history);if('mediaSession'in navigator){navigator.mediaSession.metadata=new MediaMetadata({title:s.title,artist:'SoundBreak',album:s.genre})}}catch(e){notice('Playback could not start. Tap Play on the player, or try another song.')}finally{loading=false;render();updatePlayer()}}
async function next(ended=false){if(state.remote)return command('next');if(ended===true&&state.repeat===1&&state.current)return play(state.current);let id;if(state.queue.length){const n=state.shuffle?Math.floor(Math.random()*state.queue.length):0;id=state.queue.splice(n,1)[0]}else if(state.repeat===2&&state.songs.length){state.queue=state.songs.map(s=>s.id);id=state.queue.shift()}if(id)await play(getSong(id));else{if(state.cast)castController.stop();else audio.pause();updatePlayer()}}
function previous(){if(state.remote)return command('previous');if(position()>3)return seek(0);const id=state.history.find(id=>id!==state.current?.id);if(id)play(getSong(id))}
async function toggle(){if(state.remote)return command('toggle');if(!state.current)return choose(visible()[0],visible(),0);if(state.cast){castController.playOrPause();return}try{if(audio.paused)await audio.play();else audio.pause()}catch{notice('Tap Play on the player to enable audio.')}}
function position(){return state.remote?state.remote.status?.position||0:state.cast?castPlayer?.currentTime||0:audio.currentTime}
function duration(){return state.remote?state.remote.status?.duration||0:state.cast?castPlayer?.duration||0:audio.duration}
function paused(){return state.remote?state.remote.status?.paused!==false:state.cast?castPlayer?.isPaused!==false:audio.paused}
function seek(t){if(state.remote)return command('seek',{value:t});if(state.cast){castPlayer.currentTime=t;castController.seek()}else if(Number.isFinite(audio.duration))audio.currentTime=Math.min(t,audio.duration)}
function volume(v){if(state.remote)return command('volume',{value:v});if(state.cast){castPlayer.volumeLevel=v;castController.setVolumeLevel()}else audio.volume=v}
function updatePlayer(){const d=duration(),t=position();$('#elapsed').textContent=clock(t);$('#duration').textContent=clock(d);$('#seek').value=Number.isFinite(d)&&d>0?t/d*100:0;$('#toggle').textContent=paused()?'▶':'Ⅱ';$('#toggle').setAttribute('aria-label',paused()?'Play':'Pause');$('#output').textContent=state.remote?'Remote room':state.cast?state.cast.getCastDevice().friendlyName:audio.webkitCurrentPlaybackTargetIsWireless?'AirPlay':'This device';$('#shuffle').setAttribute('aria-pressed',String(state.shuffle));$('#repeat').textContent=state.repeat===1?'↻¹':'↻';$('#repeat').classList.toggle('on',!!state.repeat);$('#repeat').setAttribute('aria-label','Repeat '+['off','one','all'][state.repeat]);if('mediaSession'in navigator)navigator.mediaSession.playbackState=paused()?'paused':'playing'}
window.__onGCastApiAvailable=function(ok){if(!ok)return;const ctx=cast.framework.CastContext.getInstance();ctx.setOptions({receiverApplicationId:chrome.cast.media.DEFAULT_MEDIA_RECEIVER_APP_ID,autoJoinPolicy:chrome.cast.AutoJoinPolicy.ORIGIN_SCOPED});castPlayer=new cast.framework.RemotePlayer();castController=new cast.framework.RemotePlayerController(castPlayer);castController.addEventListener(cast.framework.RemotePlayerEventType.ANY_CHANGE,updatePlayer);ctx.addEventListener(cast.framework.CastContextEventType.SESSION_STATE_CHANGED,async e=>{if(e.sessionState===cast.framework.SessionState.SESSION_STARTED||e.sessionState===cast.framework.SessionState.SESSION_RESUMED){state.cast=ctx.getCurrentSession();audio.pause();if(e.sessionState===cast.framework.SessionState.SESSION_STARTED&&state.current)await play(state.current);notice('Connected to '+state.cast.getCastDevice().friendlyName)}else if(e.sessionState===cast.framework.SessionState.SESSION_ENDED){state.cast=null;notice('Speaker connection ended. Choose a song to play on this device.')}updatePlayer()});let finishing=false;castController.addEventListener(cast.framework.RemotePlayerEventType.PLAYER_STATE_CHANGED,()=>{const media=state.cast?.getMediaSession();if(!loading&&!finishing&&castPlayer.playerState==='IDLE'&&media?.idleReason==='FINISHED'){finishing=true;next(true).finally(()=>finishing=false)}})};
async function api(action,data={}){const r=await fetch('api.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...data}),cache:'no-store'});let j;try{j=await r.json()}catch{throw Error('Remote service is unavailable. Local listening still works.')}if(!r.ok||j.error)throw Error(j.error||'Remote request failed');return j}
async function command(type,data={}){try{await api('command',{room:state.remote.code,type,...data});notice('Sent to player')}catch(e){notice(e.message)}}
function roomUI(){const h=state.host,r=state.remote;$('#hostDetails').hidden=!h;$('#hostButton').hidden=!!h||!!r;$('#leaveRoom').hidden=!r;$('#roomBanner').hidden=!h&&!r;if(h){$('#remoteLink').value=location.origin+location.pathname+'#room='+h.code;$('#roomBanner').textContent='Listening room is open. Keep this player awake. Share its link from Speakers & remote.'}else if(r)$('#roomBanner').textContent='Connecting to remote player…';$('#castButton').disabled=!!r;$('#airplayButton').disabled=!!r;$('#localButton').disabled=!!r}
async function join(code){try{if(code.includes('#room='))code=code.split('#room=')[1];code=code.trim().toLowerCase();if(!/^[a-f0-9]{24}$/.test(code))throw Error('Enter the full room code or remote link.');await api('status',{room:code});if(state.host)throw Error('End this listening room before joining another.');audio.pause();if(state.cast)throw Error('Return to this device before joining a remote room.');state.remote={code};location.hash='room='+code;roomUI();$('#devices').close();await poll()}catch(e){notice(e.message)}}
async function poll(){if(polling||(!state.host&&!state.remote))return;polling=true;try{if(state.host){const snapshot={song:state.current,queue:state.queue,paused:paused(),position:position(),duration:Number.isFinite(duration())?duration():0,volume:state.cast?castPlayer.volumeLevel:audio.volume,shuffle:state.shuffle,repeat:state.repeat,output:$('#output').textContent};const j=await api('heartbeat',{room:state.host.code,token:state.host.token,after:state.last,status:snapshot});for(const c of j.commands){state.last=c.id;if(c.type==='play'){if(c.song&&!getSong(c.song.id))state.songs.push(c.song);state.queue=(c.queue||[]).filter(getSong);await play(c.song)}else if(c.type==='toggle')await toggle();else if(c.type==='next')await next();else if(c.type==='previous')previous();else if(c.type==='seek')seek(c.value);else if(c.type==='volume')volume(c.value);else if(c.type==='enqueue'){if(!getSong(c.song.id))state.songs.push(c.song);state.queue.push(c.song.id)}else if(c.type==='clearQueue')state.queue=[];else if(c.type==='removeQueue')state.queue.splice(c.index,1);else if(c.type==='shuffle')state.shuffle=!state.shuffle;else if(c.type==='repeat')state.repeat=(state.repeat+1)%3}if(j.commands.length)render();$('#roomBanner').textContent='Listening room is open · '+(paused()?'Paused':'Playing')+' · Keep this player awake.'}else{const j=await api('status',{room:state.remote.code});state.remote.status=j.status;const s=j.status.song;if(s&&!getSong(s.id))state.songs.push(s);state.current=s||null;state.queue=(j.status.queue||[]).filter(getSong);state.shuffle=!!j.status.shuffle;state.repeat=j.status.repeat||0;if(s){$('#nowTitle').textContent=s.title;$('#nowGenre').textContent=s.genre;$('#nowArt').src=s.art||'art-0.svg'}$('#roomBanner').textContent=j.online?'Controlling remote player · '+(j.status.output||'This device'):'Player is offline or asleep. Keep its RPDsGrove page open to receive commands.';render()}updatePlayer()}catch(e){$('#roomBanner').textContent=e.message}finally{polling=false}}
$('#search').addEventListener('input',render);document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});$('#playAll').onclick=()=>choose(visible()[0],visible(),0);$('#newPlaylist').onclick=()=>{pendingPlaylistSong=null;newPlaylist()};$('#playlistForm').onsubmit=e=>{e.preventDefault();const name=e.target.elements.name.value.trim();if(!name)return;const p=state.playlists.find(p=>p.id===renameId);if(p)p.name=name;else state.playlists.push({id:crypto.randomUUID(),name,songs:pendingPlaylistSong?[pendingPlaylistSong]:[]});pendingPlaylistSong=null;save('playlists',state.playlists);$('#playlistDialog').close();render()};$('#nowFavorite').onclick=()=>favorite(state.current?.id);$('#toggle').onclick=toggle;$('#next').onclick=next;$('#previous').onclick=previous;$('#shuffle').onclick=()=>{if(state.remote)return command('shuffle');state.shuffle=!state.shuffle;updatePlayer()};$('#repeat').onclick=()=>{if(state.remote)return command('repeat');state.repeat=(state.repeat+1)%3;updatePlayer()};$('#seek').onchange=e=>seek(Number(e.target.value)/100*duration());$('#volume').oninput=e=>volume(Number(e.target.value));audio.volume=.7;['timeupdate','durationchange','play','pause'].forEach(t=>audio.addEventListener(t,updatePlayer));audio.onended=()=>next(true);audio.onerror=()=>notice('This song could not be loaded. Check the connection or its SoundBreak link.');
$('#mobileSettings').onclick=()=>$('#settings').showModal();$('#mobilePlaylist').onclick=()=>{pendingPlaylistSong=null;newPlaylist()};$('#settingsButton').onclick=()=>$('#settings').showModal();$('#devicesButton').onclick=()=>$('#devices').showModal();$('#addButton').onclick=()=>$('#add').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());$('#addForm').onsubmit=e=>{e.preventDefault();const f=e.target.elements,url=f.url.value.trim();if(!validUrl(url))return notice('Use a direct https://audio.soundbreak.ai/…mp3 link.');if(state.songs.some(s=>s.url===url))return notice('That song is already in your library.');const s={id:crypto.randomUUID(),title:f.title.value.trim(),genre:f.genre.value.trim()||'SoundBreak',version:'Added song',url,art:'art-0.svg'};state.songs.push(s);save('added',state.songs.filter(s=>s.version==='Added song'));$('#add').close();e.target.reset();render();notice('Song added on this device')};
const accent=read('accent','#b6e8ad');if(/^#[a-f0-9]{6}$/i.test(accent)){document.documentElement.style.setProperty('--accent',accent);$('#accent').value=accent}$('#accent').oninput=e=>{document.documentElement.style.setProperty('--accent',e.target.value);save('accent',e.target.value)};$('#resetTheme').onclick=()=>{$('#accent').value='#b6e8ad';$('#accent').dispatchEvent(new Event('input'))};
$('#castButton').onclick=async()=>{try{if(!window.cast?.framework)throw Error('Use Google Chrome on a computer on the speakers’ Wi-Fi network. Create speaker groups in Google Home first.');await cast.framework.CastContext.getInstance().requestSession()}catch(e){notice(typeof e==='string'?'Speaker connection cancelled or unavailable.':e.message||'Speaker connection unavailable.')}};$('#airplayButton').onclick=()=>{if(audio.webkitShowPlaybackTargetPicker)audio.webkitShowPlaybackTargetPicker();else notice('Open this app in Safari on an Apple device, start a song, then choose HomePods through AirPlay or Control Center.')};$('#localButton').onclick=()=>{if(state.cast){state.cast.endSession(true);state.cast=null}if(audio.webkitCurrentPlaybackTargetIsWireless)audio.webkitShowPlaybackTargetPicker();updatePlayer()};
$('#hostButton').onclick=async()=>{try{if(navigator.locks){navigator.locks.request('grove-host',{ifAvailable:true},async lock=>{if(!lock)return notice('A listening room is already running in another tab.');await startHost();await new Promise(resolve=>window.releaseHost=resolve)})}else await startHost()}catch(e){notice(e.message)}};
async function startHost(){try{const j=await api('create');state.host={code:j.room,token:j.token};state.last=0;roomUI();notice('Room started. Press Play here once before using remote playback.');if(navigator.wakeLock)navigator.wakeLock.request('screen').then(w=>window.groveWake=w).catch(()=>{});await poll()}catch(e){notice(e.message);window.releaseHost?.()}}
$('#stopRoom').onclick=async()=>{try{await api('end',{room:state.host.code,token:state.host.token});state.host=null;window.groveWake?.release();window.releaseHost?.();roomUI()}catch(e){notice(e.message)}};$('#copyLink').onclick=async()=>{try{await navigator.clipboard.writeText($('#remoteLink').value);notice('Remote link copied')}catch{$('#remoteLink').select();notice('Select and copy the link above')}};$('#joinRoom').onclick=()=>join($('#roomCode').value);$('#leaveRoom').onclick=()=>{state.remote=null;state.current=null;state.queue=[];history.replaceState(null,'',location.pathname);roomUI();updatePlayer();render()};
if('mediaSession'in navigator){for(const [a,fn]of Object.entries({play:()=>{if(paused())toggle()},pause:()=>{if(!paused())toggle()},previoustrack:previous,nexttrack:next,seekto:e=>seek(e.seekTime)}))try{navigator.mediaSession.setActionHandler(a,fn)}catch{}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;const b=el('button',{text:'Install RPDsGrove',type:'button',onclick:async()=>{await installPrompt.prompt();b.remove()}});$('#settings form').append(b)});
(async()=>{try{const r=await fetch('catalog.json');if(!r.ok)throw Error();state.songs=(await r.json()).concat(read('added',[]).filter(s=>validUrl(s.url)));render();if(location.hash.startsWith('#room='))await join(location.hash.slice(6))}catch{notice('The library could not load. Refresh when your connection returns.')}})();
const sdk=document.createElement('script');sdk.src='https://www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1';document.head.append(sdk);setInterval(poll,2000);
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});

$('#deviceVolume').onchange=e=>volume(Number(e.target.value));$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{notice('Use your browser’s full-screen option, or install the app.')}};
