'use strict';
const $=s=>document.querySelector(s), audio=$('#audio');
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem('grove:'+k))??f}catch{return f}};
const save=(k,v)=>{try{localStorage.setItem('grove:'+k,JSON.stringify(v))}catch{notice('Browser storage is full or unavailable. Changes may not be saved.')}};
const state={songs:[],view:'all',favorites:read('favorites',[]),history:read('history',[]),playlists:read('playlists',[]),queue:[],current:null,shuffle:false,repeat:0,cast:null,remote:null,host:null,last:0};
let castReady=false;let stopped=true;
let noticeTimer,castPlayer,castController,loading=false,polling=false,installPrompt=null,pendingPlaylistSong=null,renameId=null;
function notice(t){if($('#add').open){$('#importStatus').textContent=t;$('#importStatus').scrollIntoView({block:'nearest'})}if($('#devices').open)$('#deviceStatus').textContent=t;$('#notice').textContent=t;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').textContent='',6500)}
function el(tag,props={},children=[]){const n=document.createElement(tag);for(const [k,v] of Object.entries(props)){if(k==='text')n.textContent=v;else if(k==='class')n.className=v;else if(k.startsWith('on'))n.addEventListener(k.slice(2),v);else n.setAttribute(k,v)}for(const c of children)n.append(c);return n}
const button=(text,label,fn)=>el('button',{text,class:'icon','aria-label':label,onclick:fn});
const getSong=id=>state.songs.find(s=>s.id===id);
const clock=v=>Number.isFinite(v)?`${Math.floor(v/60)}:${String(Math.floor(v%60)).padStart(2,'0')}`:'0:00';
function validUrl(u){try{const x=new URL(u);return x.protocol==='https:'&&x.hostname==='audio.soundbreak.ai'&&!x.username&&!x.password&&/^\/[a-zA-Z0-9/_-]+\.mp3$/.test(x.pathname)&&!x.port&&!x.search&&!x.hash}catch{return false}}
function visible(){let a=state.songs;if(state.view==='favorites')a=a.filter(s=>state.favorites.includes(s.id));else if(state.view==='history')a=state.history.map(getSong).filter(Boolean);else if(state.view==='queue')a=state.queue.map(getSong).filter(Boolean);else if(state.view.startsWith('p:'))a=(state.playlists.find(p=>'p:'+p.id===state.view)?.songs||[]).map(getSong).filter(Boolean);const q=$('#search').value.toLowerCase();return a.filter(s=>(s.title+' '+s.genre+' '+s.version).toLowerCase().includes(q))}
function render(){const list=visible(),p=state.playlists.find(p=>'p:'+p.id===state.view);$('#viewTitle').textContent=p?.name||({all:'All songs',favorites:'Favorites',history:'Recently played',queue:'Play queue'}[state.view]||'All songs');$('#songCount').textContent=`${list.length} song${list.length===1?'':'s'}`;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));$('#playlists').replaceChildren(...state.playlists.map(p=>el('button',{text:'♫  '+p.name,class:state.view==='p:'+p.id?'active':'',onclick:()=>{state.view='p:'+p.id;render()}})));$('#playlistActions').replaceChildren();if(p){$('#playlistActions').append(el('button',{text:'Rename',onclick:()=>{renameId=p.id;$('#playlistHeading').textContent='Rename playlist';$('#playlistForm').elements.name.value=p.name;$('#playlistDialog').showModal()}}),el('button',{text:'Delete playlist',onclick:()=>{state.playlists=state.playlists.filter(x=>x.id!==p.id);save('playlists',state.playlists);state.view='all';render()}}))}if(state.view==='queue')$('#playlistActions').append(el('button',{text:'Clear queue',onclick:()=>{if(state.remote)return command('clearQueue');state.queue=[];render()}}));$('#songs').replaceChildren(...list.map((s,i)=>{const n=el('div',{class:'song'});n.append(el('span',{class:'number',text:String(i+1)}),el('button',{class:'song-play'+(state.current?.id===s.id?' current':''),onclick:()=>choose(s,list,i),'aria-label':'Play '+s.title+' '+s.genre+' '+s.version},[el('img',{src:s.art||'art-0.svg',alt:'',loading:'lazy'}),el('span',{},[el('strong',{text:s.title}),el('small',{text:s.genre+' · '+s.version})])]),el('span',{class:'genre',text:s.genre}),button(state.favorites.includes(s.id)?'♥':'♡','Favorite '+s.title,()=>favorite(s.id)),button('＋','Add '+s.title+' to queue',()=>{if(state.remote&&s.local)notice('Local files cannot be queued on a remote player.');else if(state.remote)command('enqueue',{song:s});else{state.queue.push(s.id);render();notice('Added to queue')}}),button('⋯','Add '+s.title+' to playlist',()=>choosePlaylist(s.id)));if(s.local)n.append(button('×','Remove local file '+s.title,()=>removeLocal(s)));if(p)n.append(button('−','Remove from playlist',()=>{p.songs=p.songs.filter(id=>id!==s.id);save('playlists',state.playlists);render()}));if(state.view==='queue')n.append(button('×','Remove queued song',()=>{const index=state.queue.indexOf(s.id);if(state.remote)command('removeQueue',{index});else{state.queue.splice(index,1);render()}}));return n}));if(!list.length)$('#songs').append(el('p',{class:'empty',text:state.view==='queue'?'Your queue is empty. Use + beside a song to add it.':'No songs here yet. Try another search or add songs from your library.'}));$('#nowPlaylist').disabled=!state.current;$('#nowFavorite').textContent=state.current&&state.favorites.includes(state.current.id)?'♥':'♡'}
function favorite(id){if(!id)return;state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save('favorites',state.favorites);render()}
function choosePlaylist(id){pendingPlaylistSong=id;if(!state.playlists.length){newPlaylist();return}$('#playlistChoices').replaceChildren(...state.playlists.map(p=>el('button',{text:p.name,type:'button',onclick:()=>{if(!p.songs.includes(id))p.songs.push(id);save('playlists',state.playlists);$('#choosePlaylist').close();render();notice('Added to '+p.name)}})));$('#choosePlaylist').showModal()}
function newPlaylist(){renameId=null;$('#playlistHeading').textContent='Create playlist';$('#playlistForm').reset();$('#playlistDialog').showModal()}
async function choose(s,list,i){if(s?.local&&(state.remote||state.cast)){notice('This file is stored on this device. Return to this device to play it, or add its SoundBreak link for Google speakers.');return;}if(!s)return notice('Choose a collection with songs first.');if(state.remote)return command('play',{song:s,queue:list.slice(i+1).map(x=>x.id)});state.queue=list.slice(i+1).map(x=>x.id);await play(s)}
async function play(s){if(loading)return;if(!s||!(validUrl(s.url)||(s.local&&localUrls.has(s.url))))return;if(s.local&&state.cast){notice('Local files play on this device. Add a SoundBreak link to play this song on Google speakers.');return;}loading=true;stopped=false;state.current=s;$('#nowTitle').textContent=s.title;$('#nowGenre').textContent=s.genre+' · '+s.version;$('#nowArt').src=s.art||'art-0.svg';try{if(state.cast){const m=new chrome.cast.media.MediaInfo(s.url,'audio/mpeg');m.metadata=new chrome.cast.media.MusicTrackMediaMetadata();m.metadata.title=s.title;m.metadata.artist='SoundBreak · '+s.genre;m.metadata.images=[new chrome.cast.Image(new URL('icon-512.png',location.href).href)];await state.cast.loadMedia(new chrome.cast.media.LoadRequest(m));audio.pause()}else{audio.src=s.url;await audio.play()}state.history=[s.id,...state.history.filter(id=>id!==s.id)].slice(0,100);save('history',state.history);if('mediaSession'in navigator){navigator.mediaSession.metadata=new MediaMetadata({title:s.title,artist:'SoundBreak',album:s.genre})}}catch(e){notice(state.cast?'The speaker could not load this song ('+(e.code||e.message||e)+'). Try another song, or reconnect the speaker.':'Playback could not start. Tap Play on the player, or try another song.')}finally{loading=false;render();updatePlayer()}}
async function next(ended=false){if(state.remote)return command('next');if(ended===true&&state.repeat===1&&state.current)return play(state.current);let id;if(state.queue.length){const n=state.shuffle?Math.floor(Math.random()*state.queue.length):0;id=state.queue.splice(n,1)[0]}else if(state.repeat===2&&state.songs.length){state.queue=state.songs.map(s=>s.id);id=state.queue.shift()}if(id)await play(getSong(id));else{if(state.cast)castController.stop();else audio.pause();updatePlayer()}}
function previous(){if(state.remote)return command('previous');if(position()>3)return seek(0);const id=state.history.find(id=>id!==state.current?.id);if(id)play(getSong(id))}
function stopPlayback(){if(state.remote)return command('stop');stopped=true;if(state.cast){castController.stop()}else{audio.pause();if(audio.readyState>0)audio.currentTime=0}updatePlayer()}
async function toggle(){if(state.remote)return command('toggle');if(!state.current)return choose(visible()[0],visible(),0);if(state.cast){if(!castPlayer?.isMediaLoaded)return play(state.current);castController.playOrPause();return}try{if(audio.paused){await audio.play();stopped=false}else audio.pause();updatePlayer()}catch{notice('Tap Play on the player to enable audio.')}}
function position(){return state.remote?state.remote.status?.position||0:state.cast?castPlayer?.currentTime||0:audio.currentTime}
function duration(){return state.remote?state.remote.status?.duration||0:state.cast?castPlayer?.duration||0:audio.duration}
function paused(){if(!state.remote&&stopped)return true;return state.remote?state.remote.status?.paused!==false:state.cast?castPlayer?.isPaused!==false:audio.paused}
function seek(t){if(state.remote)return command('seek',{value:t});if(state.cast){castPlayer.currentTime=t;castController.seek()}else if(Number.isFinite(audio.duration))audio.currentTime=Math.min(t,audio.duration)}
function volume(v){if(state.remote)return command('volume',{value:v});if(state.cast){castPlayer.volumeLevel=v;castController.setVolumeLevel()}else audio.volume=v}
function updatePlayer(){const d=duration(),t=position();$('#elapsed').textContent=clock(t);$('#duration').textContent=clock(d);$('#seek').value=Number.isFinite(d)&&d>0?t/d*100:0;$('#toggle').textContent=paused()?'▶':'Ⅱ';$('#toggle').setAttribute('aria-label',paused()?'Play':'Pause');const output=state.remote?(state.remote.status?.output||'Remote player'):state.cast?state.cast.getCastDevice().friendlyName:audio.webkitCurrentPlaybackTargetIsWireless?'AirPlay / HomePod':'This device';$('#output').textContent=output;const title=state.remote?(state.remote.status?.title||state.current?.title):state.current?.title;const isStopped=state.remote?state.remote.status?.stopped:stopped;$('#playingSong').textContent=title||'No song playing';$('#playingWhere').textContent=(state.remote?'Remote player: ':'Playing on: ')+output;$('#playbackState').textContent=state.remote&&state.remote.online===false?'PLAYER OFFLINE':isStopped||!title?'STOPPED':loading?'LOADING':paused()?'PAUSED':'PLAYING';$('#shuffle').setAttribute('aria-pressed',String(state.shuffle));$('#repeat').textContent=state.repeat===1?'↻¹':'↻';$('#repeat').classList.toggle('on',!!state.repeat);$('#repeat').setAttribute('aria-label','Repeat '+['off','one','all'][state.repeat]);if('mediaSession'in navigator)navigator.mediaSession.playbackState=paused()?'paused':'playing'}
window.__onGCastApiAvailable=function(ok){castReady=!!ok;if(!ok){speakerStatus();return;}const ctx=cast.framework.CastContext.getInstance();ctx.setOptions({receiverApplicationId:chrome.cast.media.DEFAULT_MEDIA_RECEIVER_APP_ID,autoJoinPolicy:chrome.cast.AutoJoinPolicy.ORIGIN_SCOPED});castPlayer=new cast.framework.RemotePlayer();castController=new cast.framework.RemotePlayerController(castPlayer);ctx.addEventListener(cast.framework.CastContextEventType.CAST_STATE_CHANGED,speakerStatus);speakerStatus();castController.addEventListener(cast.framework.RemotePlayerEventType.ANY_CHANGE,event=>{if(event.field==='playerState'&&event.value==='PLAYING')stopped=false;const info=castPlayer.mediaInfo;const match=state.songs.find(s=>s.url===info?.contentId);if(match){state.current=match;$('#nowTitle').textContent=match.title;$('#nowGenre').textContent=match.genre;$('#nowArt').src=match.art||'art-0.svg'}updatePlayer()});ctx.addEventListener(cast.framework.CastContextEventType.SESSION_STATE_CHANGED,async e=>{if(e.sessionState===cast.framework.SessionState.SESSION_STARTED||e.sessionState===cast.framework.SessionState.SESSION_RESUMED){state.cast=ctx.getCurrentSession();audio.pause();if(e.sessionState===cast.framework.SessionState.SESSION_STARTED&&state.current)await play(state.current);notice('Connected to '+state.cast.getCastDevice().friendlyName)}else if(e.sessionState===cast.framework.SessionState.SESSION_ENDED){state.cast=null;notice('Speaker connection ended. Choose a song to play on this device.')}updatePlayer()});let finishing=false;castController.addEventListener(cast.framework.RemotePlayerEventType.PLAYER_STATE_CHANGED,()=>{const media=state.cast?.getMediaSession();if(!loading&&!finishing&&castPlayer.playerState==='IDLE'&&media?.idleReason==='FINISHED'){finishing=true;next(true).finally(()=>finishing=false)}})};
async function api(action,data={}){const r=await fetch('api.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...data}),cache:'no-store'});let j;try{j=await r.json()}catch{throw Error('Remote service is unavailable. Local listening still works.')}if(!r.ok||j.error)throw Error(j.error||'Remote request failed');return j}
async function command(type,data={}){try{await api('command',{room:state.remote.code,type,...data});notice('Sent to player')}catch(e){notice(e.message)}}
function roomUI(){const h=state.host,r=state.remote;$('#hostDetails').hidden=!h;$('#hostButton').hidden=!!h||!!r;$('#leaveRoom').hidden=!r;$('#roomBanner').hidden=!h&&!r;if(h){$('#remoteLink').value=location.origin+location.pathname+'#room='+h.code;$('#roomBanner').textContent='Listening room is open. Keep this player awake. Share its link from Speakers & remote.'}else if(r)$('#roomBanner').textContent='Connecting to remote player…';$('#castButton').disabled=!!r;$('#localButton').disabled=!!r}
async function join(code){try{if(code.includes('#room='))code=code.split('#room=')[1];code=code.trim().toLowerCase();if(!/^[a-f0-9]{24}$/.test(code))throw Error('Enter the full room code or remote link.');await api('status',{room:code});if(state.host)throw Error('End this listening room before joining another.');audio.pause();if(state.cast)throw Error('Return to this device before joining a remote room.');state.remote={code};location.hash='room='+code;roomUI();$('#devices').close();await poll()}catch(e){notice(e.message)}}
async function poll(){if(polling||(!state.host&&!state.remote))return;polling=true;try{if(state.host){const snapshot={song:state.current,title:state.current?.title||'',stopped,queue:state.queue,paused:paused(),position:position(),duration:Number.isFinite(duration())?duration():0,volume:state.cast?castPlayer.volumeLevel:audio.volume,shuffle:state.shuffle,repeat:state.repeat,output:$('#output').textContent};const j=await api('heartbeat',{room:state.host.code,token:state.host.token,after:state.last,status:snapshot});for(const c of j.commands){state.last=c.id;if(c.type==='play'){if(c.song&&!getSong(c.song.id))state.songs.push(c.song);state.queue=(c.queue||[]).filter(getSong);await play(c.song)}else if(c.type==='stop')stopPlayback();else if(c.type==='toggle')await toggle();else if(c.type==='next')await next();else if(c.type==='previous')previous();else if(c.type==='seek')seek(c.value);else if(c.type==='volume')volume(c.value);else if(c.type==='enqueue'){if(!getSong(c.song.id))state.songs.push(c.song);state.queue.push(c.song.id)}else if(c.type==='clearQueue')state.queue=[];else if(c.type==='removeQueue')state.queue.splice(c.index,1);else if(c.type==='shuffle')state.shuffle=!state.shuffle;else if(c.type==='repeat')state.repeat=(state.repeat+1)%3}if(j.commands.length)render();$('#roomBanner').textContent='Listening room is open · '+(paused()?'Paused':'Playing')+' · Keep this player awake.'}else{const j=await api('status',{room:state.remote.code});state.remote.status=j.status;state.remote.online=j.online;const s=j.status.song;if(s&&!getSong(s.id))state.songs.push(s);state.current=s||null;state.queue=(j.status.queue||[]).filter(getSong);state.shuffle=!!j.status.shuffle;state.repeat=j.status.repeat||0;if(s){$('#nowTitle').textContent=s.title;$('#nowGenre').textContent=s.genre;$('#nowArt').src=s.art||'art-0.svg'}$('#roomBanner').textContent=j.online?'Controlling remote player · '+(j.status.output||'This device'):'Player is offline or asleep. Keep its RPDsGrove page open to receive commands.';render()}updatePlayer()}catch(e){$('#roomBanner').textContent=e.message}finally{polling=false}}
$('#search').addEventListener('input',render);document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;render()});$('#playAll').onclick=()=>choose(visible()[0],visible(),0);$('#newPlaylist').onclick=()=>{pendingPlaylistSong=null;newPlaylist()};$('#playlistForm').onsubmit=e=>{e.preventDefault();const name=e.target.elements.name.value.trim();if(!name)return;const p=state.playlists.find(p=>p.id===renameId);if(p)p.name=name;else state.playlists.push({id:crypto.randomUUID(),name,songs:pendingPlaylistSong?[pendingPlaylistSong]:[]});pendingPlaylistSong=null;save('playlists',state.playlists);$('#playlistDialog').close();render()};$('#nowPlaylist').onclick=()=>{if(state.current)choosePlaylist(state.current.id)};$('#nowFavorite').onclick=()=>favorite(state.current?.id);$('#stopPlayback').onclick=stopPlayback;$('#toggle').onclick=toggle;$('#next').onclick=next;$('#previous').onclick=previous;$('#shuffle').onclick=()=>{if(state.remote)return command('shuffle');state.shuffle=!state.shuffle;updatePlayer()};$('#repeat').onclick=()=>{if(state.remote)return command('repeat');state.repeat=(state.repeat+1)%3;updatePlayer()};$('#seek').onchange=e=>seek(Number(e.target.value)/100*duration());$('#volume').oninput=e=>volume(Number(e.target.value));audio.volume=.7;['timeupdate','durationchange','play','pause'].forEach(t=>audio.addEventListener(t,updatePlayer));audio.addEventListener('play',()=>{stopped=false;updatePlayer()});audio.addEventListener('webkitcurrentplaybacktargetiswirelesschanged',updatePlayer);audio.onended=()=>next(true);audio.onerror=()=>notice('This song could not be loaded. Check the connection or its SoundBreak link.');
$('#mobileSettings').onclick=()=>$('#settings').showModal();$('#mobilePlaylist').onclick=()=>{pendingPlaylistSong=null;newPlaylist()};$('#settingsButton').onclick=()=>$('#settings').showModal();$('#devicesButton').onclick=()=>{speakerStatus();$('#devices').showModal()};$('#addButton').onclick=()=>$('#add').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());$('#addForm').onsubmit=e=>{e.preventDefault();const f=e.target.elements,url=f.url.value.trim();if(!validUrl(url))return notice('Use a direct https://audio.soundbreak.ai/…mp3 link.');if(state.songs.some(s=>s.url===url))return notice('That song is already in your library.');const s={id:crypto.randomUUID(),title:f.title.value.trim(),genre:f.genre.value.trim()||'SoundBreak',version:'Added song',url,art:'art-0.svg'};state.songs.push(s);save('added',state.songs.filter(s=>s.version==='Added song'));$('#add').close();e.target.reset();render();notice('Song added on this device')};
const accent=read('accent','#b6e8ad');if(/^#[a-f0-9]{6}$/i.test(accent)){document.documentElement.style.setProperty('--accent',accent);$('#accent').value=accent}$('#accent').oninput=e=>{document.documentElement.style.setProperty('--accent',e.target.value);save('accent',e.target.value)};$('#resetTheme').onclick=()=>{$('#accent').value='#b6e8ad';$('#accent').dispatchEvent(new Event('input'))};
function speakerStatus(){
 const box=$('#deviceStatus');
 if(state.remote){box.textContent='This is a remote controller. Select Google speakers on the original player, on their Wi-Fi network.';return;}
 if(state.cast){box.textContent='Connected to '+state.cast.getCastDevice().friendlyName+'. Choose a song, then press Play.';return;}
 const ios=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
 if(ios){box.textContent='Google Cast is not available in iPhone or iPad web browsers. Open RPDsGrove in Chrome on your kiosk or computer, connect its Google speakers, then use a listening-room link to control it from this device.';return;}
 if(!castReady){box.textContent='Google Cast is unavailable in this browser or has not loaded. Open https://rdpsplace.me/rpdsgrove/ directly in Google Chrome on a computer or supported Android device, on the same Wi-Fi as the speakers. An embedded app browser may not support casting.';return;}
 const cs=cast.framework.CastContext.getInstance().getCastState();
 box.textContent=cs===cast.framework.CastState.NO_DEVICES_AVAILABLE?'Google Cast is ready, but no speakers are visible. Use the same Wi-Fi as your Nest speakers, allow local-network access if asked, and check that your speakers appear in Google Home. Guest Wi-Fi or network isolation can prevent discovery.':'Google Cast is ready. Tap Connect Google speakers and choose a speaker or Google Home group.';
}
$('#castButton').onclick=async()=>{try{if(!castReady){speakerStatus();return;}$('#deviceStatus').textContent='Opening Google’s speaker picker…';await cast.framework.CastContext.getInstance().requestSession();speakerStatus()}catch(e){const code=String(e?.code||e?.message||e);const messages={cancel:'Speaker selection was cancelled. Tap Connect Google speakers to try again.',receiver_unavailable:'No Google speaker was available. Check that this device and your speakers use the same Wi-Fi.',session_error:'The speaker connection failed. Try reconnecting in Chrome on the speakers’ Wi-Fi network.',timeout:'The speaker did not respond. Check its connection in Google Home and try again.'};notice(messages[code]||'Google speaker connection failed ('+code+'). Open the app directly in Google Chrome and try again.')}};$('#localButton').onclick=()=>{if(state.cast){state.cast.endSession(true);state.cast=null}if(audio.webkitCurrentPlaybackTargetIsWireless)audio.webkitShowPlaybackTargetPicker();updatePlayer()};
$('#hostButton').onclick=async()=>{try{if(navigator.locks){navigator.locks.request('grove-host',{ifAvailable:true},async lock=>{if(!lock)return notice('A listening room is already running in another tab.');await startHost();await new Promise(resolve=>window.releaseHost=resolve)})}else await startHost()}catch(e){notice(e.message)}};
async function startHost(){try{const j=await api('create');state.host={code:j.room,token:j.token};state.last=0;roomUI();notice('Room started. Press Play here once before using remote playback.');if(navigator.wakeLock)navigator.wakeLock.request('screen').then(w=>window.groveWake=w).catch(()=>{});await poll()}catch(e){notice(e.message);window.releaseHost?.()}}
$('#stopRoom').onclick=async()=>{try{await api('end',{room:state.host.code,token:state.host.token});state.host=null;window.groveWake?.release();window.releaseHost?.();roomUI()}catch(e){notice(e.message)}};$('#copyLink').onclick=async()=>{try{await navigator.clipboard.writeText($('#remoteLink').value);notice('Remote link copied')}catch{$('#remoteLink').select();notice('Select and copy the link above')}};$('#joinRoom').onclick=()=>join($('#roomCode').value);$('#leaveRoom').onclick=()=>{state.remote=null;state.current=null;state.queue=[];history.replaceState(null,'',location.pathname);roomUI();updatePlayer();render()};
if('mediaSession'in navigator){for(const [a,fn]of Object.entries({play:()=>{if(paused())toggle()},pause:()=>{if(!paused())toggle()},stop:stopPlayback,previoustrack:previous,nexttrack:next,seekto:e=>seek(e.seekTime)}))try{navigator.mediaSession.setActionHandler(a,fn)}catch{}}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;const b=el('button',{text:'Install RPDsGrove',type:'button',onclick:async()=>{await installPrompt.prompt();b.remove()}});$('#settings form').append(b)});
const localUrls=new Set();
let musicDB;
function openMusicDB(){if(!musicDB)musicDB=new Promise((resolve,reject)=>{const r=indexedDB.open('rpdsgrove-music',1);r.onupgradeneeded=()=>r.result.createObjectStore('files',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});return musicDB}
async function fileStore(action,value){const db=await openMusicDB();return new Promise((resolve,reject)=>{const tx=db.transaction('files',action==='getAll'?'readonly':'readwrite'),r=tx.objectStore('files')[action](...(value===undefined?[]:[value]));tx.oncomplete=()=>resolve(r.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('Storage unavailable'))})}
function localSong(row){const url=URL.createObjectURL(row.file);localUrls.add(url);return {id:row.id,title:row.name.replace(/\.[^.]+$/,''),genre:'Local file',version:'On this device',url,local:true,art:'art-0.svg'}}
async function restoreLocal(){try{const rows=await fileStore('getAll');state.songs.push(...rows.map(localSong))}catch{notice('Local music storage is unavailable. SoundBreak links still work.')}}
async function removeLocal(s){try{await fileStore('delete',s.id);if(state.current?.id===s.id){audio.pause();audio.removeAttribute('src');state.current=null;$('#nowTitle').textContent='Choose your soundtrack';$('#nowGenre').textContent='RPDsGrove · SoundBreak'}URL.revokeObjectURL(s.url);localUrls.delete(s.url);state.songs=state.songs.filter(x=>x.id!==s.id);state.queue=state.queue.filter(id=>id!==s.id);render();notice('Local file removed from this browser')}catch{notice('Could not remove the local file.')}}
async function importFiles(files,playlist=null){let added=0,skipped=0,failed=0;const imported=[];const status=$('#importStatus');$('#folderFiles').disabled=$('#musicFiles').disabled=$('#importAll').disabled=$('#importToPlaylist').disabled=true;try{for(const file of files){if(!/\.(mp3|wav|m4a|ogg|flac|aac)$/i.test(file.name)||file.size===0||file.size>100*1024*1024){skipped++;continue}status.textContent='Importing '+file.name+'…';try{const bytes=await file.arrayBuffer();const digest=await crypto.subtle.digest('SHA-256',bytes);const id='local-'+Array.from(new Uint8Array(digest)).map(b=>b.toString(16).padStart(2,'0')).join('');if(state.songs.some(s=>s.id===id)){imported.push(id);skipped++;continue}const row={id,name:file.name,file};await fileStore('put',row);state.songs.push(localSong(row));imported.push(id);added++}catch{failed++}}if(playlist&&imported.length){if(!state.playlists.some(p=>p.id===playlist.id))state.playlists.push(playlist);playlist.songs=[...new Set([...playlist.songs,...imported])];save('playlists',state.playlists)}state.view='all';$('#search').value='';render();status.textContent=`${added} song${added===1?'':'s'} added. ${skipped?skipped+' skipped (duplicate, unsupported or over 100 MB). ':''}${failed?failed+' could not be saved. Browser storage may be full.':''}${playlist&&imported.length?' Added to playlist: '+playlist.name+'.':''}`;pendingFiles=[];$('#selectedFiles').hidden=true;}finally{$('#folderFiles').disabled=$('#musicFiles').disabled=$('#importAll').disabled=$('#importToPlaylist').disabled=false;$('#folderFiles').value='';$('#musicFiles').value=''}}
let pendingFiles=[];
function selectImportFiles(files){if(!files.length)return;pendingFiles=files;$('#selectedFiles').hidden=false;$('#selectedSummary').textContent=files.length===1?'Selected: '+files[0].name:files.length+' files selected';$('#importStatus').textContent='Choose where to add your selection.';$('#importPlaylist').replaceChildren(...state.playlists.map(p=>el('option',{value:p.id,text:p.name})),el('option',{value:'new',text:'Create a new playlist'}));$('#newImportPlaylistLabel').hidden=$('#importPlaylist').value!=='new';$('#importAll').scrollIntoView({block:'center'});$('#importAll').focus({preventScroll:true});}
$('#folderFiles').onchange=e=>selectImportFiles(Array.from(e.target.files));$('#musicFiles').onchange=e=>selectImportFiles(Array.from(e.target.files));$('#importPlaylist').onchange=()=>$('#newImportPlaylistLabel').hidden=$('#importPlaylist').value!=='new';$('#importAll').onclick=()=>importFiles(pendingFiles);$('#importToPlaylist').onclick=()=>{let playlist=state.playlists.find(p=>p.id===$('#importPlaylist').value);if(!playlist){const name=$('#newImportPlaylist').value.trim();if(!name){$('#importStatus').textContent='Enter a name for your new playlist.';$('#newImportPlaylist').focus();return}playlist={id:crypto.randomUUID(),name,songs:[]}}importFiles(pendingFiles,playlist)};
(async()=>{try{const r=await fetch('catalog.json');if(!r.ok)throw Error();state.songs=(await r.json()).concat(read('added',[]).filter(s=>validUrl(s.url)));await restoreLocal();render();if(location.hash.startsWith('#room='))await join(location.hash.slice(6))}catch{notice('The library could not load. Refresh when your connection returns.')}})();
const sdk=document.createElement('script');sdk.src='https://www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1';sdk.onerror=()=>{castReady=false;speakerStatus()};document.head.append(sdk);setInterval(poll,2000);
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});

$('#deviceVolume').onchange=e=>volume(Number(e.target.value));$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{notice('Use your browser’s full-screen option, or install the app.')}};

$('#returnToKiosk').onclick=()=>location.assign('/');
$('#returnToKioskApp').onclick=()=>{if(document.documentElement.dataset.kioskReturn==='ready')window.dispatchEvent(new Event('rpdsgrove:return'));else notice('To return to the kiosk app, open RPDsGrove using its button on the kiosk home screen. This browser is not connected to the kiosk launcher.');};
